//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.29 at 11:04:23 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pad.polito.it/dp2/biblio")
package it.polito.pad.dp2.biblio;
