//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:09:35 PM CET 
//


package it.polito.dp2.rest.gbooks.client.valueTypes;

import javax.xml.bind.annotation.XmlType;

@XmlType(name = "IndustryIdentifier")
public class IndustryIdentifier {

    protected String type;
    protected String identifier;

    public String getType() {
        return type;
    }

    public void setType(String value) {
        this.type = value;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String value) {
        this.identifier = value;
    }

}
