//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:09:35 PM CET 
//


package it.polito.dp2.rest.gbooks.client.valueTypes;

import javax.xml.bind.annotation.XmlType;


@XmlType(name = "Items")
public class Items {

    protected String selfLink;
    protected VolumeInfo volumeInfo;

    public String getSelfLink() {
        return selfLink;
    }

    public void setSelfLink(String value) {
        this.selfLink = value;
    }

    public VolumeInfo getVolumeInfo() {
        return volumeInfo;
    }

    public void setVolumeInfo(VolumeInfo value) {
        this.volumeInfo = value;
    }

}
