//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:09:35 PM CET 
//


package it.polito.dp2.rest.gbooks.client.valueTypes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlType;


@XmlType(name = "SearchResult")
public class SearchResult {

    protected BigInteger totalItems;
    protected List<Items> items;

   public BigInteger getTotalItems() {
        return totalItems;
    }

    public void setTotalItems(BigInteger value) {
        this.totalItems = value;
    }

    public List<Items> getItems() {
        if (items == null) {
            items = new ArrayList<Items>();
        }
        return this.items;
    }

}
