//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.14 at 07:09:35 PM CET 
//


package it.polito.dp2.rest.gbooks.client.valueTypes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import it.polito.dp2.rest.gbooks.client.valueTypes.IndustryIdentifier;


@XmlType(name = "VolumeInfo")
public class VolumeInfo {

    protected String title;
    protected String subtitle;
    @XmlSchemaType(name = "string")
    protected List<String> authors;
    protected String publisher;
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar publisherDate;
    @XmlSchemaType(name = "IndustryIdentifier")
    protected List<IndustryIdentifier> industryIdentifiers;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pageCount;

    public String getTitle() {
        return title;
    }

    public void setTitle(String value) {
        this.title = value;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String value) {
        this.subtitle = value;
    }
    public List<String> getAuthors() {
        if (authors == null) {
            authors = new ArrayList<String>();
        }
        return this.authors;
    }

    public String getPublisher() {
        return publisher;
    }

    public void setPublisher(String value) {
        this.publisher = value;
    }

    public XMLGregorianCalendar getPublisherDate() {
        return publisherDate;
    }

    public void setPublisherDate(XMLGregorianCalendar value) {
        this.publisherDate = value;
    }

    public List<IndustryIdentifier> getIndustryIdentifiers() {
        return industryIdentifiers;
    }

    public BigInteger getPageCount() {
        return pageCount;
    }

    public void setPageCount(BigInteger value) {
        this.pageCount = value;
    }

}
