//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.05 at 05:16:11 PM CET 
//


package it.polito.dp2.rest.gbooks.client.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="selfLink" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="volumeInfo" type="{}VolumeInfo"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "items")
public class Items {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String selfLink;
    @XmlElement(required = true)
    protected VolumeInfo volumeInfo;

    /**
     * Gets the value of the selfLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfLink() {
        return selfLink;
    }

    /**
     * Sets the value of the selfLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfLink(String value) {
        this.selfLink = value;
    }

    /**
     * Gets the value of the volumeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeInfo }
     *     
     */
    public VolumeInfo getVolumeInfo() {
        return volumeInfo;
    }

    /**
     * Sets the value of the volumeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeInfo }
     *     
     */
    public void setVolumeInfo(VolumeInfo value) {
        this.volumeInfo = value;
    }

}
