//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.02 at 06:42:09 PM CET 
//


package it.polito.dp2.BIB.sol2.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.BIB.sol2.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.BIB.sol2.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MyPathReq }
     * 
     */
    public MyPathReq createMyPathReq() {
        return new MyPathReq();
    }

    /**
     * Create an instance of {@link MyNodeBody }
     * 
     */
    public MyNodeBody createMyNodeBody() {
        return new MyNodeBody();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link it.polito.dp2.BIB.sol2.jaxb.Data }
     * 
     */
    public it.polito.dp2.BIB.sol2.jaxb.Data createData() {
        return new it.polito.dp2.BIB.sol2.jaxb.Data();
    }

    /**
     * Create an instance of {@link MyRelationship }
     * 
     */
    public MyRelationship createMyRelationship() {
        return new MyRelationship();
    }

    /**
     * Create an instance of {@link MyPath }
     * 
     */
    public MyPath createMyPath() {
        return new MyPath();
    }

    /**
     * Create an instance of {@link MyPathList }
     * 
     */
    public MyPathList createMyPathList() {
        return new MyPathList();
    }

    /**
     * Create an instance of {@link MyRelationshipBody }
     * 
     */
    public MyRelationshipBody createMyRelationshipBody() {
        return new MyRelationshipBody();
    }

    /**
     * Create an instance of {@link MyNode }
     * 
     */
    public MyNode createMyNode() {
        return new MyNode();
    }

    /**
     * Create an instance of {@link MyPathReq.ReturnFilter }
     * 
     */
    public MyPathReq.ReturnFilter createMyPathReqReturnFilter() {
        return new MyPathReq.ReturnFilter();
    }

    /**
     * Create an instance of {@link MyPathReq.PruneEvaluator }
     * 
     */
    public MyPathReq.PruneEvaluator createMyPathReqPruneEvaluator() {
        return new MyPathReq.PruneEvaluator();
    }

    /**
     * Create an instance of {@link MyPathReq.Relationships }
     * 
     */
    public MyPathReq.Relationships createMyPathReqRelationships() {
        return new MyPathReq.Relationships();
    }

    /**
     * Create an instance of {@link MyNodeBody.Data }
     * 
     */
    public MyNodeBody.Data createMyNodeBodyData() {
        return new MyNodeBody.Data();
    }

}
