//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 01:35:59 PM CET 
//


package it.polito.dp2.rest.neo4j.client.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.rest.neo4j.client.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.rest.neo4j.client.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PathReq }
     * 
     */
    public PathReq createPathReq() {
        return new PathReq();
    }

    /**
     * Create an instance of {@link NodeBody }
     * 
     */
    public NodeBody createNodeBody() {
        return new NodeBody();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link RelationshipBody }
     * 
     */
    public RelationshipBody createRelationshipBody() {
        return new RelationshipBody();
    }

    /**
     * Create an instance of {@link PathReq.Relationships }
     * 
     */
    public PathReq.Relationships createPathReqRelationships() {
        return new PathReq.Relationships();
    }

    /**
     * Create an instance of {@link NodeBody.Metadata }
     * 
     */
    public NodeBody.Metadata createNodeBodyMetadata() {
        return new NodeBody.Metadata();
    }

    /**
     * Create an instance of {@link NodeBody.Data }
     * 
     */
    public NodeBody.Data createNodeBodyData() {
        return new NodeBody.Data();
    }

}
